---
title: 'Report for UK Weather Stations'
output: word_document
params:
  station: NA
  y_axis: NA,
  aggregation: NA,
  x_axis: NA
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

# Imports
library('ggplot2')
library('dplyr')
library('magrittr')
library('glue')
library('vroom')
library('lubridate')
library('ggrepel')
library('maps')
library('mapproj')
library('shiny')

# Initial Load of Data ----
sites <- vroom('./Data/Prepared Data Files For App/Sites.csv')
file_names <- dir(path = './Data/Prepared Data Files For App/Inidividual Sites/')
# Make sure to only load csv's to ensure local/cloud compatibility
file_names <- file_names[grepl('.csv', file_names)]
setwd('./Data/Prepared Data Files For App/Inidividual Sites/')
all_data <- do.call(rbind,lapply(file_names,read.csv))

# Transform ob_time into datetime
all_data$ob_time <- lubridate::as_datetime(all_data$ob_time)

# Transform site id into character data type
all_data$Site <- as.character(all_data$Site)
sites$Site_ID <- as.character(sites$Site_ID)

# Filter the desired sites
selected_data <- all_data %>%
  filter(Site %in% params$station)  

# Perform Selected Aggregation ----

# Aggregate daily averages
if (params$aggregation == 'davg_agg'){
  agg_data <- selected_data %>% 
    group_by(month, day, Site) %>% 
    summarise(ob_time = first(ob_time),
              wind_speed = mean(wind_speed),
              air_temperature = mean(air_temperature),
              rltv_hum = mean(rltv_hum),
              visibility = mean(visibility), 
              Site = first(Site))

# Aggregate monthly averages
} else if (params$aggregation == 'mavg_agg'){
  agg_data <- selected_data %>% 
    group_by(month, Site) %>% 
    summarise(ob_time = first(ob_time),
              wind_speed = mean(wind_speed),
              air_temperature = mean(air_temperature),
              rltv_hum = mean(rltv_hum),
              visibility = mean(visibility), 
              Site = first(Site))
  
# Aggregate daily maxima  
} else if (params$aggregation == 'dmax_agg'){
  agg_data <- selected_data %>% 
    group_by(month, day, Site) %>% 
    summarise(ob_time = first(ob_time),
              wind_speed = max(wind_speed),
              air_temperature = max(air_temperature),
              rltv_hum = max(rltv_hum),
              visibility = max(visibility), 
              Site = first(Site))
  
# Aggregate daily minima    
} else if (params$aggregation == 'dmin_agg'){
  agg_data <- selected_data %>% 
    group_by(month, day, Site) %>% 
    summarise(ob_time = first(ob_time),
              wind_speed = min(wind_speed),
              air_temperature = min(air_temperature),
              rltv_hum = min(rltv_hum),
              visibility = min(visibility), 
              Site = first(Site))

# No aggregation
} else {agg_data <- selected_data}

# Handling of x-axis ----

if (params$x_axis == 'hourw_time'){
  
  final_data <- agg_data %>%
    mutate(weekday = wday(ob_time,
                          week_start = getOption('lubridate.week.start', 1)),
           ob_time = (weekday - 1) * 24 + hour)


} else if (params$x_axis == 'dayw_time'){
  
  final_data <- agg_data %>%
    mutate(ob_time = wday(ob_time,
                          label = TRUE,
                          week_start = getOption('lubridate.week.start', 1)))
  
} else if (params$x_axis == 'hourd_time'){
  
  final_data <- agg_data %>%
    mutate(ob_time = strftime(ob_time, format='%H'))
  
} else {final_data <- agg_data}

dataset <- final_data

# Handle x and y label of plots ----

# The following function formats the x-axis label
x_label <- function(x_axis){
  
  if (x_axis == 'cal_time') return('Calendar Time')
  else if (x_axis == 'hourw_time') return('Hour of the Week')
  else if (x_axis == 'dayw_time') return('Weekday')
  else return('Hour of the Day')
  
}

# The following function formats the x-axis label
y_label <- function(y_axis){
  
  if (y_axis == 'wind_speed') return('Wind Speed (Knots)')
  else if (y_axis == 'air_temperature') return('Air Temperature (Celsius)')
  else if (y_axis == 'rltv_hum') return('Relative Humidity (%)')
  else return('Visibility (m)')
  
}

# The following function formats the title
plot_title <- function(aggregation, y_axis){
  
  if (aggregation == 'no_agg'){
    
    if (y_axis == 'wind_speed') return('Hourly Data for Wind Speed')
    else if (y_axis == 'air_temperature') return('Hourly Data for Air Temperature')
    else if (y_axis == 'rltv_hum') return('Hourly Data for Relative Humidity')
    else return('Hourly Data for Visibility')
    
  } else if (aggregation == 'davg_agg'){
    
    if (y_axis == 'wind_speed') return('Daily Average for Wind Speed')
    else if (y_axis == 'air_temperature') return('Daily Average for Air Temperature')
    else if (y_axis == 'rltv_hum') return('Daily Average for Relative Humidity')
    else return('Daily Average for Visibility')
    
  } else if (aggregation == 'mavg_agg'){
    
    if (y_axis == 'wind_speed') return('Monthly Average for Wind Speed')
    else if (y_axis == 'air_temperature') return('Monthly Average for Air Temperature')
    else if (y_axis == 'rltv_hum') return('Monthly Average for Relative Humidity')
    else return('Monthly Average for Visibility')
    
  } else if (aggregation == 'dmax_agg'){
    
    if (y_axis == 'wind_speed') return('Daily Maxima for Wind Speed')
    else if (y_axis == 'air_temperature') return('Daily Maxima for Air Temperature')
    else if (y_axis == 'rltv_hum') return('Daily Maxima for Relative Humidity')
    else return('Daily Maxima for Visibility')
    
  } else {
    
    if (y_axis == 'wind_speed') return('Daily Minima for Wind Speed')
    else if (y_axis == 'air_temperature') return('Daily Minima for Air Temperature')
    else if (y_axis == 'rltv_hum') return('Daily Minima for Relative Humidity')
    else return('Daily Minima for Visibility')
    
  }
  
}
```

## Plot For Selected Input

```{r main_plot, echo = FALSE}

# Inner join to get the name of the sites
plot_data <- dataset %>%
  inner_join(sites, by = c('Site' = 'Site_ID'))

# Start plot...
plot <- ggplot(data = plot_data) +          # Set data source
  aes_string(x = 'ob_time',                 # ob_time always on x-axis
             y = params$y_axis,             # y-axis according to input
             color = 'Site_Name') +         # Color always by site
  ggtitle(plot_title(input$aggregation,     # Set plot title
                         input$y_axis)) +
  xlab(x_label(params$x_axis)) +            # Set x-axis label
  ylab(y_label(params$y_axis)) +            # Set y-axis label
  theme_bw() +                              # Change the theme
  theme(legend.position = 'bottom', 
        legend.direction = 'horizontal',
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 8),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        plot.title = element_text(size = 14))

# ...decide between line and scatter plot
if (params$x_axis == 'cal_time'){
  plot <- plot + geom_line(size = 1.05, alpha = 0.7)
} else {
  plot <- plot + geom_point(size = 3, alpha = 0.5)
  }

plot

```


## Location of Weather Stations

```{r map_plot, echo = FALSE}

map_data <- dataset %>%
  inner_join(sites, by = c('Site' = 'Site_ID')) %>%   # Get long/lat for selected sites
  group_by(Site_Name) %>% 
  summarise(Latitude = first(Latitude),
            Longitude = first(Longitude))

UK <- map_data(map = 'world', region = 'UK')     # Get spatial data for the UK
map <- ggplot() + 
  geom_polygon(aes(x = UK$long,                  # Draw shape of the UK
                   y = UK$lat,
                   group = UK$group)) +
  coord_map() +
  theme(axis.line = element_blank(),             # Remove all chart elements
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = 'none',
        panel.background = element_blank(),
        plot.title = element_text(size = 16, face = 'bold'),
        plot.margin = margin(0, 0, 0, -5, 'cm'))

if (is.null(params$station) == FALSE){            # If the user selects a station...
  
  map <- map +                                   # ... add location of the stations...
    geom_point(aes(map_data$Longitude,
                   map_data$Latitude,
                   color = map_data$Site_Name,   # ... with same color as main plot
                   fill = map_data$Site_Name,
                   size = 10),
               shape = 20) +
    geom_label_repel(aes(map_data$Longitude,    # Add label to station's location
                        map_data$Latitude,
                        label = map_data$Site_Name,
                        color = map_data$Site_Name),
                     size = 4)
}

map

```

## Data For Last Seven Days

```{r table, echo = FALSE}

table_data <- all_data %>%
  filter(Site %in% params$station) %>% 
  filter(ob_time > '2020-11-24') %>%                           # Filter the last 7 days
  inner_join(sites, by = c('Site' = 'Site_ID')) %>%            # Get names of sites
  mutate(ob_time = paste('2020', month, day, sep = '/')) %>%   # Construct date
  group_by(ob_time, Site_Name) %>%
  summarise('Wind Speed' = mean(wind_speed),
            'Air Temperature' = mean(air_temperature),
            'Relative Humidity' = mean(rltv_hum),
            'Visibility' = mean(visibility)) %>% 
  rename('Date' = ob_time,
         'Site' = Site_Name)

knitr::kable(table_data)

```
